version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: atlas_postgres
    environment:
      POSTGRES_DB: atlas_poc
      POSTGRES_USER: atlas_user
      POSTGRES_PASSWORD: atlas_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: atlas_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: